# for development environment - uses local .env.development file and mounts backend code for live updates

# specify the version of docker-compose
version: "3.8"

# define the services/containers to be run
services:
  # define the api service/container
  api:
    
    # specify the ports to expose for the api service
    # the first number is the port on the host machine
    # the second number is the port inside the container
    ports: 
      - "4013:4013"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/app

    # specify environment variables for the api service
    # these environment variables will be read from the .env file
    env_file: 
      - .env.development

    # establish docker compose watch mode for the api service
    develop:
      # specify the files to watch for changes
      watch:
        # watch package.json and package-lock.json for changes
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild

        # watch backend source files and sync changes with the container in real time
        - path: ./src
          target: /app
          action: sync
